<?php

namespace App\DataFixture;

use App\Entity\User;
use Fidry\AliceDataFixtures\ProcessorInterface;
use Symfony\Component\PasswordHasher\Hasher\UserPasswordHasherInterface;

/**
 * Give all users generated by fixtures, password "password".
 */
class UserProcessor implements ProcessorInterface
{
    private UserPasswordHasherInterface $passwordHasher;

    public function __construct(UserPasswordHasherInterface $passwordHasher)
    {
        $this->passwordHasher = $passwordHasher;
    }

    public function preProcess(string $id, $object): void
    {
        if (false === $object instanceof User) {
            return;
        }
        $object->updatePassword($this->passwordHasher->hashPassword($object, 'password'));
    }

    public function postProcess(string $id, $object): void
    {

    }
}