vich_uploader:
    db_driver: orm
    storage: flysystem

    metadata:
        type: attribute

    mappings:
        image:
            upload_destination: images.storage
            namer:
                service: Vich\UploaderBundle\Naming\PropertyNamer
                options: { property: id }
            inject_on_load: false
            delete_on_update: true
            delete_on_remove: true
